apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: wanderlust
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "gzEeAPnALMsfTefnkr5Ft5wCbWHEWJVDlb1kMvFC5c8="
            - name: MYSQL_DATABASE
              value: "PROD_WARMUP"
            - name: MYSQL_USER
              value: "XGROWTH"
            - name: MYSQL_PASSWORD
              value: "gzEeAPnALMsfTefnkr5Ft5wCbWHEWJVDlb1kMvFC5c8="
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: wanderlust
spec:
  selector:
    app: mongo
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
